### ISSUE TITLE
Validation performance of LM

### ISSUE THREAD

**Issue by cstorm125** [n-waves/ulmfit-multilingual#11]
How do you validate the performance of your LM in your respective languages? 

Assuming that we are training on varying size of wikis, I tried 20% and 1% holdouts. The 20% has the perplexity of about 46 (a little higher than reported for English) and the 1% has 30. Thai wiki is 1.6G.

**Comment by PiotrCzapla** [comment]
@cstorm125 Have a look at the scripts in `master` we cut out a validation and test sets and we keep it the same for all sizes of the Wikipedia sets (2m, 100m, all tokens). As discussed here the perplexity depends on the vocabulary size and the number of OOV of a test set.  
See discussion here:
https://github.com/n-waves/ulmfit-multilingual/issues/3
