### ISSUE TITLE
Improve the way we run experiments - saving, hyper params selection

### ISSUE THREAD

**Issue by PiotrCzapla** [n-waves/ulmfit-multilingual#17]
I want to address the following issues:
1. there are quite a few collisions in the way models are saved currently, for example, different tokenization strategies may reuse the same tokens which is obviously incorrect.
2. no easy way to select tokenization strategy currently it is selected by boolean parameters which isn't the best way to address it
3. all the hyper-parameters must be passed externally via command line arguments from pretrain_lm to train_clas, which is super error prone.

Here is how I'm inteding to fix this:
## re. 1
Each LM model will get's its own folder under which all files are saved (itos, weights, sp.model etc), Each Classfication model will be stored undert the LM model folder under it's own folder name. This will give us a quick way to remove the experiments we don't want, more over we will know exactly how the models were created. Here is an example structure:
``` 
-  data/wiki/wikitext-103/models/
    - sp_nh4_30epoch.m
          - itos.pkl
          - sp.model
          - sp.vocab
          - info.json # all hyper params, and the performance info 
          - train.log
          - weights.pth
          - imdb/large-head.m
               - itos.pkl
               - sp.model
               - sp.vocab
               - info.json
               - train.log
               - weights-e1.pth
               - weights-e10.pth
               - weights-e100.pth
               - weights-best.pth
```
## re. 2
Instead of boleans we will simply select the startegy by name

## re. 3
I will make it easy to get the required hyper-params from the pretrain lm model selected (info.json), plus we will make it possible to define some experiments directly in python and refere to them by name.

**Comment by dust0x** [comment]
Great idea, completely agree on all three points. With regards to 2: Moses tokenizer is used irrespective of whether we want to use subword tokenization or not, which, I think justifies the boolean flag. That being said, if, say, at some point we decide to include spacy or any other method, we will have to re-write the code in the way you recommend so we may as well do it now.
