### ISSUE TITLE
Add test to check the whole pipeline

### ISSUE THREAD

**Issue by PiotrCzapla** [n-waves/ulmfit-multilingual#2]
Add a test to check the whole pipeline and show how to train a classification task for EN (I'm working on it)

**Comment by NirantK** [comment]
Hey @PiotrCzapla I came across some minor bugs while working with trying to train English and Hindi using `pretrain_lm` - I have pushed the fixes to master *just this once*. 

I will make future changes in a separate branch.

**Comment by PiotrCzapla** [comment]
btw @NirantK  it seems that you managed to run the whole thing end to end, do you want to take over this issue and create a small test (small artificial dataset) where the whole process is executed. Ie LM trained, classification trained, & tested? So that we can use it to see if our scripts are still working after updates to fastai.

**Comment by NirantK** [comment]
As of now, I am figuring out the small fixes needed in classifier to make it in English and at least one other language. I'll do this as we build the XNLI and Wikipedia classifier or immediately after.

**Comment by PiotrCzapla** [comment]
@NirantK  then commit please to master the fixes as I"m going to need that soon to double check the performance of BILM

**Comment by PiotrCzapla** [comment]
test added:
https://github.com/n-waves/ulmfit-multilingual/commit/23b17da61eff4f8bc0d2ddfa9aff66a5112e0a2b
