### ISSUE TITLE
Calculation of Perplexity ins't working  (refactoring and master branch)

### ISSUE THREAD

**Issue by alexwwang** [n-waves/ulmfit-multilingual#22]
I find that when computing test logloss and perplexity here: [https://github.com/n-waves/ulmfit-multilingual/blob/eea9be09db8520ad87d28551a88a728e170c455e/ulmfit/pretrain_lm.py#L167](https://github.com/n-waves/ulmfit-multilingual/blob/eea9be09db8520ad87d28551a88a728e170c455e/ulmfit/pretrain_lm.py#L167)
the data `trn_path` points at is used but `tst_path` points at.

Is this a typo or mean to do this? 

Since I found the test data is never used during pretrain_lm section, I intend to accept this is a typo.

**Comment by PiotrCzapla** [comment]
I guess it is typo, the code is changed completely in refactoring branch so check it there. But I wasn't paying attention to the perplexity as it does not translate to the performance of downstream tasks so I guess the code isn't working.

**Comment by PiotrCzapla** [comment]
If you want to play with the perplexity calculation let me know and create PR based on  refactoring branch.

**Comment by PiotrCzapla** [comment]
I've added perplexity calculation in https://github.com/n-waves/ulmfit-multilingual/tree/multifit as sotabench script.
