### ISSUE TITLE
Compare QRNN Performance Metrics

### ISSUE THREAD

**Issue by eisenjulian** [n-waves/ulmfit-multilingual#35]
We need to create benchmarks to prove the performance gains of QRNN. @sebastianruder do you mind helping out with a guideline of what are the best measurements and variables to control for.

I am thinking of fixing vocabulary size to 15 or 30k. Comparing the speed of QRNN and LSTM.
1) Language-Model (1K training sentences of length bptt)
2) Unfrozen Classifier (1K training examples)

Is that what you had in mind?

**Comment by sebastianruder** [comment]
Yep, that's what I had in mind. I think vocabulary size of 30k is good.

**Comment by eisenjulian** [comment]
Created a pull request here #37
