### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by cahya-wirawan** [n-waves/ulmfit-multilingual#41]
Hi Piotr, 

I tried the "pytest ." on your repo, but I got following error message, maybe the current language_model_learner() in fastai  is not compatible anymore with your code:

```
platform linux -- Python 3.7.2, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/cahya/Work/Machine Learning/FastAI/ulmfit-multilingual, inifile:
plugins: xdist-1.27.0, forked-1.0.2
collected 13 items

tests/test_end_to_end.py F...FFF                                         [ 53%]
tests/test_text_data.py FF                                               [ 69%]
tests/test_text_train.py EFFF                                            [100%]

==================================== ERRORS ====================================
_______________________ ERROR at setup of test_val_loss ________________________

    @pytest.fixture(scope="module")
    def learn():
        path, df_trn, df_val = prep_human_numbers()
        data = TextLMDataBunch.from_df(path, df_trn, df_val, tokenizer=Tokenizer(BaseTokenizer))
>       learn = language_model_learner(data, emb_sz=100, nl=1, drop_mult=0.1)
E       TypeError: language_model_learner() missing 1 required positional argument: 'arch'

/home/cahya/Work/Machine Learning/FastAI/ulmfit-multilingual/tests/test_text_train.py:39: TypeError
...
```

**Comment by eisenjulian** [comment]
Thanks for spotting this, it seems some of those tests got stale. @PiotrCzapla I took a pass at fixing some of the issues here https://github.com/n-waves/ulmfit-multilingual/compare/fix-tests?expand=1 and the remaining issue seems to be the `lm_type` arg for backward and bidirectional models, we are not using any of those anymore, correct? Should I just remove them or is there a plan to bring that back to life?

**Comment by PiotrCzapla** [comment]
Thank you Julian!, Yeah let's remove them, the bidir wasn't working as expected and there is no point in keeping that.

**Comment by eisenjulian** [comment]
Should be fixed now, thanks again for the report
