### ISSUE TITLE
The argument bs is not known

### ISSUE THREAD

**Issue by cahya-wirawan** [n-waves/ulmfit-multilingual#42]
I tried to run 
`python -m ulmfit lm --dataset-path data/wiki/wikitext-103 --bidir=False --qrnn=False --tokenizer=vf --name 'bs40' --bs=40 --cuda-id=0  -  train 20 --drop-mult=0.9
...` as mentioned in readme file, but I get this error message: 
`TypeError: __init__() got an unexpected keyword argument 'bs'`
It seems the class LMHyperParams doesn't have this batch size option.

**Comment by gedwadr** [comment]
@cahya-wirawan I got the same problem as well, have you solved it? Thank you

**Comment by cahya-wirawan** [comment]
For time being, I just removed the argument  "--bs=40" from the command line. bs is set to 70 by default.

**Comment by PiotrCzapla** [comment]
Hi Cahya the bs parameter was moved to train, let me update the docs.
