### ISSUE TITLE
Is it possible to load several "learn" models at a time?

### ISSUE THREAD

**Issue by basque21** [n-waves/ulmfit-multilingual#48]
I don't understand very well how the model works, but I was wondering if each classification model is loading the language model independently and then doing the evaluation. I want to use it for production with different classification datasets, but each of them need a lot of CPU memory.

**Comment by PiotrCzapla** [comment]
LM is being updated for each classification task so it is slightly different. You could implement multitask learning to get the optimisation you are looking for, but I would start directly from fastai to do so it will be easier than using this repo.
